server:
  port: 8080

spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: rest-service
          uri: http://localhost:8082
          predicates:
            - Path=/users
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:4000/auth/realms/Omega/protocol/openid-connect/token
            authorization-uri: http://localhost:4000/auth/realms/Omega/protocol/openid-connect/auth
            user-info-uri: http://localhost:4000/auth/realms/Omega/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          my_client_a:
            provider: keycloak
            client-id: Omega
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

logging:
  level:
    org:
      springframework:
        security: DEBUG