server:
  port: 8080

spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      routes:
        - id: rest-service
          uri: http://localhost:8082
          predicates:
            - Path=/users