server:
  port: 8082

spring:
  application:
    name: rest-service
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4000/realms/Omega